# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end

target 'MCCordovaPluginLib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'MarketingCloudSDK', '~> 7.4'
	pod 'Cordova', '~> 4.5.4'

  # Pods for MCCordovaPluginLib
  target 'Tests' do
    inherit! :search_paths
    pod 'OCMock', '~> 3.4.3'

  end
	
	

end
